CREATE TABLE novels
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    author_id INTEGER NOT NULL,
    abstract TEXT NOT NULL,
    cover_image VARCHAR(255) NOT NULL,
    publication_date TIMESTAMP NOT NULL,
    FOREIGN KEY (author_id) REFERENCES authors (id)
);

INSERT INTO novels (name, author_id, abstract, cover_image, publication_date) VALUES
('Ascendance of a Bookworm', 1, 'A certain college girl who is loved books ever since she was a little girl dies in an accident and is reborn in another world she knows nothing about. She is now Myne, the sickly five-year-old daughter of a poor soldier. To make things worse, the world she is been reborn in has a very low literacy rate and books mostly  do not exist. she would have to pay an enormous amount of money to buy one. Myne resolves herself: If there are not any books, she will just have to make them! Her goal is to become a librarian. This story begins with her quest to make books so she can live surrounded by them! Dive into this biblio-fantasy written for book lovers and bookworms!', 'Ascendance of a Bookworm/Ascendance of a Bookworm.png', '2020-12-03 00:00:00'),
('By the Grace of the Gods', 2, 'Under the protection of the gods, a relaxed life with slimes in another world begins! One day, the life of middle-aged Japanese businessman Ryoma Takebayashi came to a rather sudden and disappointing end. Ryoma had never had a blessed life, but after his death, three great gods sought his cooperation and reincarnated him as a child in another world with swords and magic! Receiving a most cordial and divine welcome from the gods, Ryoma decides to live leisurely on his own in the forest for the time being. Working diligently at magic and hunting, Ryoma is greatest passion comes to be researching his tamed slimes?! Training a variety of slimes (some newly discovered), the curtain rises on this easygoing life fantasy celebrating a second life with kind people in another world!', 'By the Grace of the Gods/By the Grace of the Gods.png', '2016-03-10 00:00:00'),
('I Parry Everything', 3, 'The Kingdom of Clays faces a dire crisis: an assassination attempt has just been made on its own Princess Lynneburg, and its neighboring countries eye the aftermath like starving vultures, plotting the Kingdom is downfall. The ensuing conflict will shape the face of the continent for centuries to come...but Noor does not have a clue about any of that! Having freshly arrived at the royal capital after over a decade of rigorous, isolated training at his mountain home, he is dead set on achieving his childhood dream of becoming an adventurer, even if the only skills he possesses are useless ones. Sure, he can [Parry] thousands of swords in the span of a single breath, but everybody knows you need more than that if you want to be an adventurer! Our hero is road to making his dream come true will be long(?) and arduous(?)—but if there is one thing Noor is not afraid of, it is some good old fashioned hard work!', 'I Parry Everything/I Parry Everything.png', '2021-01-07 00:00:00'),
('I Shall Survive Using Potions!', 4, 'One day, the supervisor in charge of watching over Earth was taking care of a distortion, when they made a mistake that caused Kaoru Nagase to lose her physical body. Not only that, but reincarnating her into a different, less culturally advanced world is the only thing they can offer to do for her. Not one to take this turn of events sitting down, Kaoru makes a demand: the power to create potions at any time she pleases, with whatever effect she wants it to have—and it does not stop there either. She asks for a magical Item Box, the ability to understand and speak every language, and the same body she had back when she was a fifteen-year-old girl. Using her newfound powers, Kaoru has to try and make a stable life for herself in a whole new world!', 'I Shall Survive Using Potions!/I Shall Survive Using Potions!.png', '2020-12-03 00:00:00'),
('Isekai Tensei', 5, 'After waking up at his own funeral, Tenma Otori gets a second chance at life when a god from another world presents him with an enticing offer: if Tenma agrees to be reincarnated in order to save their dying world, the gods will bestow cheat abilities upon him. Tenma accepts, and is reborn in a lush fantasy world filled with demi-humans, magic spells and items, monsters, mysterious forests, and more! As he grows, more of his gods-given powers and abilities—including his unique power to befriend adorable monsters like slimes and baby wolves—are revealed to his adoptive parents, two former master adventurers, and his grandfather, a famous wizard. But one fateful day, three mysterious strangers shatter the tranquility of Tenma is village by trying to kidnap him, and that is where Tenma is adventure really begins...', 'Isekai Tensei/Isekai Tensei.png', '2020-12-03 00:00:00'),
('Little Witch Academia', 6, 'I am Atsuko Kagari, but you can call me Akko! It is been my lifelong dream to become. Awitch, and I came all the way from Japan to attend the prestigious Luna Nova Witchcraft Academy. But then I found out all we ever do is study, study, study! I swear! What is with this place?! Well, we finally left our desks to go on a class trip to Doras Hill, and things were going smoothly for once!...That is, until I met the guardian of the hill, Sifla. Wait, whadja say, Sifla? Did your cat and dog run away from home?  do not worry. Lotte, Sucy, and I will find them for you! After all, we are three hearts that beat as one, right?', 'Little Witch Academia/Little Witch Academia.png', '2020-12-03 00:00:00'),
('Magic Knight of the Old Ways', 7, 'A long, long time ago, in the era of legends, there was a knight known as Sir Sid the Barbarian who pledged his sword to the Holy King Arthur. Unparalleled in strength, he was the greatest magical knight of his time, but also a disgrace to the name of chivalry. His evil deeds were countless, and eventually he met his end at the hands of his own king...or so the story goes. Now a thousand years have passed, and Sid is summoned from his eternal slumber by Alvin, a descendant of Arthur and a prince who knows the truth about Sir Sid the Lightning Knight. Honoring his ancient pact, Sid rises from the grave to help Alvin save the kingdom from impending peril and become the new instructor to Alvin is class of fellow aspiring knights. As danger lurks in the shadows, Sid must train this class of underdogs to rely on more than just their magical fairy swords and teach them the old ways of the magic knights.', 'Magic Knight of the Old Ways/Magic Knight of the Old Ways.png', '2021-01-07 00:00:00'),
('Mushoku Tensei', 8, 'A 34-years-old NEET otaku is chased out from his house by his family. This virgin, plump, unattractive, and penniless nice guy found that his life are going down the path to an end, He then recalled that his life could actually be much better if he can get over the dark history of his life. Just when he was at the point of regret, he saw a truck moving at fast speed, and 3 high-schoolers in it is path. Mustering all strength he had, he tried to save them and ended getting run over by the truck, quickly ending his life. The next time he opened his eyes, he is already reincarnated to a world of sword and magic as Rudeus Greirad. Born to a new world, a new life, Rudeus decided that, [This time, I will really live my life to the fullest with no regret!]. Thus start the journey of a man yearning to restart his life.', 'Mushoku Tensei/Mushoku Tensei.png', '2014-01-23 00:00:00'),
('My Magical Career at Court', 9, 'Magic is everything to Noelle. She loves it so much that she puts up with her horrible job at the Mages Guild to practice it. The hours are long, the pay is rock-bottom, and the boss is a nightmare! But as long as she has magic, she can withstand the hardships. At least, until the day she hears these dreaded words:“You are fired.” Noelle is hometown in the outskirts of the kingdom does not offer many alternatives for a career in magic—especially now that she is been blacklisted from guild work! Just when it seems like all hope is lost, Noelle is old friend Luke shows up to give her an opportunity she never could have imagined: a job as a royal court magician. Now Noelle is living the dream, rubbing shoulders with the kingdom is greatest magicians and showing off her skills. She has a beautiful new workplace and a generous new boss, but how will she cope with intense entrance exams, her marriage-obsessed mother, and the rules of etiquette? What awaits Noelle in her magical new career?', 'My Magical Career at Court/My Magical Career at Court.png', '2021-01-07 00:00:00'),
('Reincarnated as the Last of My Kind', 10, 'Getting reincarnated in another world populated by humans, demi-humans, and mythical beasts is certainly not the turn I thought my life was going to take. I especially did not expect to be carried off by a wolf and given into the care of a one-armed former knight! Now I am trying to repay him by rebuilding the family inn and healing his arm with alchemy. But the more time passes, the more it becomes clear to me that I am not actually human...', 'Reincarnated as the Last of My Kind/Reincarnated as the Last of My Kind.png', '2021-01-07 00:00:00'),
('Solo Leveling', 11, 'E-rank hunter Jinwoo Sung has no money, no talent, and no prospects to speak of-and apparently, no luck, either! When he enters a hidden double dungeon one fateful day, he is abandoned by his party and left to die at the hands of some of the most horrific monsters he is ever encountered. But just before the last, fatal blow… PING! [Congratulations on becoming a Player.]', 'Solo Leveling/Solo Leveling.png', '2016-11-04 00:00:00'),
('That Time I Got Reincarnated as a Slime', 12, 'A man is stabbed by a robber on the run after pushing his coworker and his coworker is new fiance out of the way. As he lays dying, bleeding on the ground, he hears a voice. This voice is strange and interprets his dying regret of being a virgin by giving him the [Great Sage] unique skill! Is he being made fun of !?!', 'That Time I Got Reincarnated as a Slime/That Time I Got Reincarnated as a Slime.png', '2014-01-23 00:00:00'),
('The Alchemist Who Survived Now Dreams of a Quiet City Life', 13, 'Alchemists used to be a dime a dozen in the Kingdom of Endalsia, so Mariela was never particularly special. But her skills were put to the test one fateful day when a horde of monsters came stampeding from the nearby forest. In a desperate attempt to escape the horror, the young alchemist put herself in a state of suspended animation that lasted just a little longer than she would planned—an entire two hundred years! Needless to say, there have been some big changes, and biggest of all: Mariela is now the sole alchemist in the entire kingdom. Her one wish in this strange new environment is to get back her quiet, leisurely, low-key lifestyle!', 'The Alchemist Who Survived Now Dreams of a Quiet City Life/The Alchemist Who Survived Now Dreams of a Quiet City Life.png', '2018-12-21 00:00:00'),
('The Apothecary Diaries', 14, 'In the East is a land ruled by an emperor, whose consorts and serving women live in a sprawling complex known as the hougong, the rear palace. Maomao, an unassuming girl raised in an unassuming town by her apothecary father, never imagined the rear palace would have anything to do with her—until she was kidnapped and sold into service there. Though she looks ordinary, Maomao has a quick wit, a sharp mind, and an extensive knowledge of medicine. That is her secret, until she encounters a resident of the palace at least as perceptive as she is: the head eunuch, Jinshi. He sees through Maomao is façade and makes her a lady-in-waiting to none other than the Emperor is favorite consort… so she can taste the lady is food for poison! At her lady is side, Maomao starts to learn about everything that goes on in the rear palace—not all of it seemly. Can she ever lead a quiet life, or will her powers of deduction and insatiable curiosity bring her ever more adventures, and ever more dangers?', 'The Apothecary Diaries/The Apothecary Diaries.png', '2021-01-07 00:00:00'),
('The Brilliant Healer''s New Life in the Shadows', 15, 'Life has not been kind to Zenos. He was born in the slums, and his dirt-poor background has denied him almost every opportunity. After an encounter with a healer, he throws himself into studying to become one and finally catches a break when an adventurer invites Zenos into his party. Zenos is thrilled—so thrilled, in fact, that he is willing to put up with his teammates treating him like garbage. They fail to appreciate his talents and ultimately kick him to the curb, claiming he is outlived his usefulness to them. Now bereft of money and out of options, Zenos decides to put his self-taught skills to use elsewhere and opens an underground clinic. Word quickly spreads about the brilliant healer working incredible magic in the city is shadowy underbelly. Even the royal palace is taking notice... Can Zenos buck the odds and carve out a life for himself in a world that is spit in his face? And can he save the lives of the patients who wind up on his doorstep in the process?', 'The Brilliant Healer''s New Life in the Shadows/The Brilliant Healer''s New Life in the Shadows.png', '2022-02-20 00:00:00'),
('The Irregular at Magic High School', 16, 'The year is 2095. Magic has been tamed as another form of technology, and the practice of magic is now a rigorous discipline. Brother and sister Tatsuya and Miyuki Shiba are just about to start their first year at the renowned First Magic High School of Japan. But the school is ironclad rules mean that the brilliant Miyuki enters the prestigious Course 1, while her older brother, Tatsuya, is relegated to Course 2--and that is just the beginning of their troubles!', 'The Irregular at Magic High School/The Irregular at Magic High School.png', '2014-01-23 00:00:00'),
('The Saint''s Magic Power is Omnipotent', 17, 'Sei is first journey abroad in this other world is to Zaidera and she is trying her hand at making magical amulets! She is also over the moon about her engagement to Albert. While busy with wedding preparations, Sei overhears how one of the members of First Prince Kyle is delegation to Zaidera is now bedridden with an unknown illness. Naturally, Sei cannot just stand idly by, and, with that, her trip to Zaidera is hurriedly assured. However, upon her arrival, Kyle informs Sei that no one is sick and to make matters worse, the port has been closed, so they are now stuck abroad!', 'The Saint''s Magic Power is Omnipotent/The Saint''s Magic Power is Omnipotent.png', '2021-01-07 00:00:00'),
('The World''s Finest Assassin Gets Reincarnated in Another World', 18, 'At long last, the academy has finished repairs after the first demon attack, and Lugh returns to school. What awaits him is a wild request from his upperclassman, Nevan Romalung. She tasks him with killing demons impersonating the Pope of the Alamite Church! Monsters and villains are one thing, but to assassinate the leader of the largest religion in the world is a very different story…', 'The World''s Finest Assassin Gets Reincarnated in Another World/The World''s Finest Assassin Gets Reincarnated in Another World.png', '2021-01-07 00:00:00');

